### ISSUE TITLE
Placeholders with uppercase characters never displayed

### ISSUE THREAD

**Issue by dule** [Datananas/quill-placeholder-autocomplete#10]
If you have placeholders containing uppercase characters, they are never displayed in the list of suggestions. The problem appears to be because the labels being passed into `FuzzySet` [here](https://github.com/Datananas/quill-placeholder-autocomplete/blob/80555afb0f7e07c3a7a2ff8bd4267679b995e621/src/autocomplete-module.js#L215) are being lower-cased. So when retrieving the results from `FuzzySet`, the results will also be lowercase, and will never match any uppercase-containing placeholders when filtering [here](https://github.com/Datananas/quill-placeholder-autocomplete/blob/80555afb0f7e07c3a7a2ff8bd4267679b995e621/src/autocomplete-module.js#L248).

The thing is, I don't think you need to lowercase the values passed to FuzzySet. FuzzySet normalizes the values (i.e., does it's own lower-casing) for the purposes of matching, and will return the original labels in the results.

**Comment by sotaan** [comment]
Wow! I’ll check that tomorow morning

**Comment by sotaan** [comment]
PR is merged along with the other one you provided.
Many thanks again for your contributions
